# Generated by Django 5.1.1 on 2024-11-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="SpotifyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_user_id", models.CharField(max_length=50, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayedTrack",
            fields=[
                ("stream_id", models.AutoField(primary_key=True, serialize=False)),
                ("track_id", models.CharField(max_length=50)),
                ("played_at", models.DateTimeField()),
                ("track_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("album_name", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.spotifyuser",
                    ),
                ),
            ],
        ),
    ]
