# Generated by Django 5.1.1 on 2024-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="PlayedTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("track_id", models.CharField(max_length=50)),
                ("played_at", models.DateTimeField()),
                ("track_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("album_name", models.CharField(max_length=200)),
            ],
        ),
    ]
