# Generated by Django 5.1.1 on 2024-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playedtrack",
            name="played_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="playedtrack",
            name="track_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
