# Generated by Django 5.1.1 on 2024-11-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_user_id", models.CharField(max_length=50, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="playedtrack",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.spotifyuser"
            ),
        ),
    ]
