# Generated by Django 5.1.1 on 2024-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_alter_playedtrack_played_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifyuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="spotifyuser",
            name="spotify_user_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
