# Generated by Django 5.1.1 on 2024-11-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_alter_spotifyuser_display_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifyuser",
            name="id",
        ),
        migrations.AlterField(
            model_name="spotifyuser",
            name="spotify_user_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
