# Generated by Django 5.1.1 on 2024-12-01 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_alter_playedtrack_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playedtrack",
            unique_together={("user", "stream_id", "played_at")},
        ),
    ]
