# Generated by Django 5.1.1 on 2024-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_alter_playedtrack_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="playedtrack",
            name="duration_ms",
            field=models.BigIntegerField(default=0),
        ),
    ]
