# Generated by Django 5.1.1 on 2024-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_playedtrack_duration_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="playedtrack",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="playedtrack",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
