# Generated by Django 5.1.1 on 2024-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_playedtrack_genres_playedtrack_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="playedtrack",
            name="album_id",
            field=models.CharField(db_index=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playedtrack",
            name="artist_id",
            field=models.CharField(db_index=True, default=0, max_length=50),
            preserve_default=False,
        ),
    ]
