# Generated by Django 5.1.1 on 2024-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="spotify_user_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
