# Generated by Django 5.1.1 on 2024-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_spotifytoken_spotify_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="access_token",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="scope",
            field=models.CharField(max_length=500),
        ),
    ]
